
Options:
  Debug: false
  Language: en_US
  Auto-Reload-Files: true

Load-Script-Files:
  - 'plugins/CustomScriptFolder'

Default-Script-Options:
  Main: execute
  Engine: nashorn

  Import:
    server:
      type: STATIC
      object:
        class: 'org.bukkit.Bukkit'
        args: []
      method:
        name: 'getServer'
        args: []

    utils:
      type: STATIC
      object:
        class: 'me.scoretwo.fastscript.utils.Assist'
        args: []
      method:
        name: 'instance'
        args: []